version: '3'
services:
  iedc_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iedc_backend
    image: iedc_backend
    restart: always
    ports:
      - "8003:8000"
    volumes:
      - /var/log/iedc_backend:/var/log/iedc_backend
    env_file:
      - .env
