# Generated by Django 4.1.6 on 2023-09-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=uuid.UUID('d9d07b46-ff0a-4a42-b5fe-cfe14cd75d27'), max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=75)),
                ('muid', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(max_length=36, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission.py', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.CharField(default=uuid.UUID('65af4dae-4727-4598-bc99-0cc9b0a1381b'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'flash_card',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=uuid.UUID('7cad6b75-d8a3-491e-90b0-ae84ed44e9d6'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='LearningStation',
            fields=[
                ('id', models.CharField(default=uuid.UUID('35044848-7756-462c-8833-02a867965483'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'learning_station',
            },
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.CharField(default=uuid.UUID('3169e70f-f333-46e6-832d-34748c8af956'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('data', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'qr_code',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(default=uuid.UUID('2eddb9dd-9581-4054-bae1-a874dfe1cf71'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=300, unique=True)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.CharField(default=uuid.UUID('50ca143f-eeb8-42c3-8d3d-dd998dd28701'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reward',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=uuid.UUID('abb52b24-ded3-41e2-b477-d804c99abac3'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserRoleLink',
            fields=[
                ('id', models.CharField(default=uuid.UUID('1cae4b07-7c7b-4c65-8999-7fa0f8bd509c'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_link_role', to='dashboard.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_link_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role_link',
            },
        ),
        migrations.CreateModel(
            name='UserRewardLink',
            fields=[
                ('id', models.CharField(default=uuid.UUID('09c75189-1791-41b0-9dfb-adef87cdaef8'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reward_link_reward', to='dashboard.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reward_link_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_reward_link',
            },
        ),
        migrations.CreateModel(
            name='UserQrCodeLink',
            fields=[
                ('id', models.CharField(default=uuid.UUID('08d901a5-50f3-4e83-8206-5c5fc877455d'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_qr_code_link_qr_code', to='dashboard.qrcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_qr_code_link_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_qr_code_link',
            },
        ),
        migrations.CreateModel(
            name='UserGroupLink',
            fields=[
                ('id', models.CharField(default=uuid.UUID('6f2c1a86-270d-4e04-83a9-85b64d6c799b'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_link_group', to='dashboard.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_link_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_group_link',
            },
        ),
        migrations.CreateModel(
            name='UserFlashCardLink',
            fields=[
                ('id', models.CharField(default=uuid.UUID('3f24f692-585f-495b-a538-a81eded9571d'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('flash_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flash_card_link_flash_card', to='dashboard.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flash_card_link_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_flash_card_link',
            },
        ),
        migrations.CreateModel(
            name='LearningStationQuizLink',
            fields=[
                ('id', models.CharField(default=uuid.UUID('b49c31c2-0a20-4fc5-833f-f8a4e925a559'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('learning_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_station_quiz_link_learning_station', to='dashboard.learningstation')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_station_quiz_link_quiz', to='dashboard.quiz')),
            ],
            options={
                'db_table': 'learning_station_quiz_link',
            },
        ),
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.CharField(default=uuid.UUID('e8d0c7e3-b40c-4c20-8f9d-577ce097a344'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forgot_password',
            },
        ),
    ]
