# Generated by Django 4.1.6 on 2023-09-29 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("2aaf9978-1173-44c1-8b6a-9cdfe6d61d42"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=75)),
                ("muid", models.CharField(max_length=100, unique=True)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "qr_code",
                    models.CharField(
                        default=uuid.UUID("3fc51394-224a-4b79-8b48-4ea851dca9e0"),
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("20411bf5-144c-486b-9a87-e0c1036e9a0f"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "flash_card",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("7a8bc7e1-84c3-42f9-a5ed-3cb2ce4f19f0"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "group",
            },
        ),
        migrations.CreateModel(
            name="LearningStation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("baac33e7-4877-492b-bea2-78db58402073"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "learning_station",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("de65c250-574b-4ef1-86a0-338c1e8eabe9"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "reward",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("5ee4f01e-752e-4492-88d5-021abbf9f59b"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="UserRoleLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("313a343b-ff73-4379-87b0-5710923d37bc"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_link_role",
                        to="dashboard.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_role_link",
            },
        ),
        migrations.CreateModel(
            name="UserRewardLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("0fe6c7b9-3e29-4e0a-be38-4f4a6ad83d02"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reward_link_reward",
                        to="dashboard.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reward_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_reward_link",
            },
        ),
        migrations.CreateModel(
            name="UserGroupLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("21605930-f8cb-4eb0-adf5-50cb2a3d90e1"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_group_link_group",
                        to="dashboard.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_group_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_group_link",
            },
        ),
        migrations.CreateModel(
            name="UserFlashCardLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("c2068c8d-9b04-4b3e-97c1-c5196e40006e"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "flash_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_flash_card_link_flash_card",
                        to="dashboard.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_flash_card_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_flash_card_link",
            },
        ),
        migrations.CreateModel(
            name="ForgetPassword",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("d7e91eff-2847-4331-ac12-7f18ed9692b4"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("otp", models.CharField(max_length=6, unique=True)),
                ("expiry", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forgot_password_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forgot_password",
            },
        ),
    ]
