# Generated by Django 4.1.6 on 2023-09-27 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("6023b65d-1faf-4d77-a059-84a60f1b7999"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=75)),
                ("muid", models.CharField(max_length=100, unique=True)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("edd36bbb-dabf-44d8-a47f-2751ffcf430c"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "flash_card",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("62ff077e-3b43-44d2-86c9-f2bd4009e237"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "group",
            },
        ),
        migrations.CreateModel(
            name="LearningStation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("61c5e614-d9cc-45f8-a711-8df59ed345a1"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "learning_station",
            },
        ),
        migrations.CreateModel(
            name="QrCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("27dd89e7-ec3c-4ced-a27c-f4aab419a139"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("data", models.CharField(max_length=100, unique=True)),
                ("type", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "qr_code",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("3c0273b5-f153-46ae-ae8d-b0a94fd0990e"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("question", models.CharField(max_length=250, unique=True)),
                ("option_a", models.CharField(max_length=200)),
                ("option_b", models.CharField(max_length=200)),
                ("option_c", models.CharField(max_length=200)),
                ("option_d", models.CharField(max_length=200)),
                ("answer", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "quiz",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("294185ee-226e-41af-9d96-35f70d6f238f"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "reward",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("0e0894eb-6512-44be-8bb6-a879e596aea9"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="UserRoleLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("f46136e6-4036-4cff-acb4-ca7d1d29593a"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_link_role",
                        to="dashboard.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_role_link",
            },
        ),
        migrations.CreateModel(
            name="UserRewardLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("e65a86dd-2361-41ce-abfa-5088f1975f8e"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reward_link_reward",
                        to="dashboard.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reward_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_reward_link",
            },
        ),
        migrations.CreateModel(
            name="UserQrCodeLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("e11fa497-4313-46bb-bb1e-601b8eab0b15"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_qr_code_link_qr_code",
                        to="dashboard.qrcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_qr_code_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_qr_code_link",
            },
        ),
        migrations.CreateModel(
            name="UserGroupLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("452569cf-7aa0-46b8-9a33-4011116591bd"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_group_link_group",
                        to="dashboard.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_group_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_group_link",
            },
        ),
        migrations.CreateModel(
            name="UserFlashCardLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("9e1996fa-8bf6-48d6-9f05-35d2094f420f"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "flash_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_flash_card_link_flash_card",
                        to="dashboard.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_flash_card_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_flash_card_link",
            },
        ),
        migrations.CreateModel(
            name="LearningStationQuizLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("2e65710d-cdf1-462e-b28d-cce33dc90891"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "learning_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_station_quiz_link_learning_station",
                        to="dashboard.learningstation",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_station_quiz_link_quiz",
                        to="dashboard.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "learning_station_quiz_link",
            },
        ),
        migrations.CreateModel(
            name="ForgetPassword",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("23d0eb28-eba2-4c2d-90b5-2685c7f0b39f"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("otp", models.CharField(max_length=6, unique=True)),
                ("expiry", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forgot_password_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forgot_password",
            },
        ),
    ]
